#!/bin/bash
# Set IFS to colon to split fields in /etc/passwd
IFS=':'

# Read /etc/passwd line by line
while read -r username password userid groupid userinfo homedir shell
do
    # Format and print the user information
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
